// Code generated by optgen. DO NOT EDIT.
package settings

// ApplyTo assigns the current value to a target entity.
func (value Builder) ApplyTo(entity interface{}) {
	if target, ok := entity.(interface {
		SetBuilder(Builder)
	}); ok {
		target.SetBuilder(value)
	}
}

// SetBuilder assigns value to the current target.
func (target *Builder) SetBuilder(value Builder) {
	*target = value
}
