// Code generated by optgen. DO NOT EDIT.
package settings

import (
	"github.com/4rcode/gadget"
)

type Builder [1]gadget.Builder

func (value Builder) ApplyTo(entity interface{}) {
	if target, ok := entity.(interface {
		SetBuilder(Builder)
	}); ok {
		target.SetBuilder(value)
	}
}

func (target *Builder) SetBuilder(value Builder) {
	*target = value
}
