// Code generated by optgen. DO NOT EDIT.
package settings

type Format string

func (value Format) ApplyTo(entity interface{}) {
	if target, ok := entity.(interface {
		SetFormat(Format)
	}); ok {
		target.SetFormat(value)
	}
}

func (target *Format) SetFormat(value Format) {
	*target = value
}
