// Code generated by optgen. DO NOT EDIT.
package settings

type NegativeFormat string

func (value NegativeFormat) ApplyTo(entity interface{}) {
	if target, ok := entity.(interface {
		SetNegativeFormat(NegativeFormat)
	}); ok {
		target.SetNegativeFormat(value)
	}
}

func (target *NegativeFormat) SetNegativeFormat(value NegativeFormat) {
	*target = value
}
