// Code generated by optgen. DO NOT EDIT.
package settings

import (
	"github.com/4rcode/gadget"
)

type Reporters []gadget.Reporter

func (value Reporters) ApplyTo(entity interface{}) {
	if target, ok := entity.(interface {
		SetReporters(Reporters)
	}); ok {
		target.SetReporters(value)
	}
}

func (target *Reporters) SetReporters(value Reporters) {
	if len(value) < 1 {
		*target = nil
	} else {
		*target = append(*target, value...)
	}
}
