// Code generated by optgen. DO NOT EDIT.
package settings

type Separator string

func (value Separator) ApplyTo(entity interface{}) {
	if target, ok := entity.(interface {
		SetSeparator(Separator)
	}); ok {
		target.SetSeparator(value)
	}
}

func (target *Separator) SetSeparator(value Separator) {
	*target = value
}
