// Code generated by optgen. DO NOT EDIT.
package settings

type StringFormat string

func (value StringFormat) ApplyTo(entity interface{}) {
	if target, ok := entity.(interface {
		SetStringFormat(StringFormat)
	}); ok {
		target.SetStringFormat(value)
	}
}

func (target *StringFormat) SetStringFormat(value StringFormat) {
	*target = value
}
