// Code generated by optgen. DO NOT EDIT.
package settings

type Template string

func (value Template) ApplyTo(entity interface{}) {
	if target, ok := entity.(interface {
		SetTemplate(Template)
	}); ok {
		target.SetTemplate(value)
	}
}

func (target *Template) SetTemplate(value Template) {
	*target = value
}
