on:
  push:
    branches: [1.0]
  pull_request:
    branches: [1.0]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17.0
      - run: go get ./...
      - run: go install github.com/4rcode/gnomic/cmd/optgen@1.0
      - run: go generate ./...
      - run: go test ./... -cover -count=1 -coverprofile='coverage.txt'
      - uses: codecov/codecov-action@v2
